[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
gpui = { git = "https://github.com/wuliuqii/zed", branch = "layer-shell" }
ui = { path = "crates/ui" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
incremental = false
opt-level = "z"
strip = true
rpath = false
debug = false
debug-assertions = false
overflow-checks = false
