[package]
name = "mgs"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/wuliuqii/zed", branch = "layer-shell" }

tokio = { version = "1", features = ["full"] }
chrono = "0.4.39"
hyprland = "0.4.0-beta.2"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = "0.3.19"
