[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
zbus.workspace = true
futures-signals = "0.3.34"
tracing.workspace = true
itertools.workspace = true

[dev-dependencies]
tokio.workspace = true
